[phases.setup]
nixPkgs = ["nodejs", "npm", "php83", "php83Extensions.gd", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build]
cmds = [
    "npm run build",
    "php artisan storage:link"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"